# .goreleaser.yaml
before:
  hooks:
    # Run go mod tidy to ensure dependencies are clean
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/slothctl/main.go
    binary: slothctl
    # Windows specific settings
    goarm:
      - 6
      - 7
    # Skip ARM builds for Windows
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .ProjectName }}-{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  # GitHub release settings
  github:
    owner: chalkan3
    name: slothctl
  # Add release notes
  footer: |
    ## Installation

    Download the appropriate binary for your system from the assets above.

    ## Checksums

    Verify your download with the checksums file.
