// Code generated by go generate; DO NOT EDIT.
// This file was generated by pkg/commands/generate.go

package zz_generated_commands

import (
	_ "github.com/chalkan3/slothctl/pkg/commands/configure"
	_ "github.com/chalkan3/slothctl/pkg/commands/glpi"
	_ "github.com/chalkan3/slothctl/pkg/commands/glpi/tickets"
	_ "github.com/chalkan3/slothctl/pkg/commands/server"
	_ "github.com/chalkan3/slothctl/pkg/commands/vpn"
)
